GET  http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWU5YTg4MzU3OTU4Y2UyNWE4ZjgwMSIsImlhdCI6MTY3MjQxNTc3MiwiZXhwIjoxNjcyNDE5MzcyLCJpc3MiOiJqc29ud2VidG9rZW4ifQ.b_0kV5ftolrLei3nsFXXM3LkX9sDi3sD4OYLuWD-Mec


###
GET  http://localhost:3000/abc


###
POST  http://localhost:3000/auth/register
Content-Type: application/json


{
    "email": "pavtar144@gmail.com",
    "password": "1234567"
}


###
POST  http://localhost:3000/auth/login
Content-Type: application/json


{
    "email": "pavtar1234@gmail.com",
    "password": "1234567"
}


###
POST  http://localhost:3000/auth/refresh-token
Content-Type: application/json


{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWU5YTg4MzU3OTU4Y2UyNWE4ZjgwMSIsImlhdCI6MTY3MjQxNTc3MiwiZXhwIjoxNzAzOTczMzcyLCJpc3MiOiJqc29ud2VidG9rZW4ifQ.TcvCIhm-AccfFCf4VI2VXb8AUSls_tWHASxL7CMzLrk"
}


###
POST  http://localhost:3000/auth/logout